// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FPC_Kern_S
List FPC_Kern_S(NumericVector x, NumericVector t, IntegerVector N, double h1, double h2);
RcppExport SEXP _PPFPCA_FPC_Kern_S(SEXP xSEXP, SEXP tSEXP, SEXP NSEXP, SEXP h1SEXP, SEXP h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< double >::type h2(h2SEXP);
    rcpp_result_gen = Rcpp::wrap(FPC_Kern_S(x, t, N, h1, h2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PPFPCA_FPC_Kern_S", (DL_FUNC) &_PPFPCA_FPC_Kern_S, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PPFPCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
