---
title: "Multicore Computing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{scalability}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = TRUE,
  collapse = TRUE
)
options(width=100)
```

```{r}
library(PETLER)
```

```{r}
TrainCode <- data_org$TrainCode
TrainCode[, monthstd := month / fu_time]  
TrainCode
```

```{r}
colSums(TrainCode[, 4:6])
```

```{r}
timing <- function(code, ngrid, n_core) {
  x <- seq(0, 1, length.out = ngrid)  
  pred <- TrainCode[[code]]
  TrainNP <- pred[pred > 0] 
  t <- rep(TrainCode$monthstd, pred)
  h1 <- bw.nrd(t)
  h2 <- bw.nrd(t)^(5/6)  
  system.time(FPC.Kern.S(x, t, TrainNP, h1, h2, n_core = n_core))["elapsed"]
}
```

```{r}
# timing(code = "pred1", ngrid = 101, n_core = 4)
```

```{r, eval=FALSE, echo=FALSE}
DF <- expand.grid(
  codes = paste0("pred", 1:3), 
  ngrid =  c(100, 200, 400) + 1, 
  n_core = c(1, 2, 4),
  time = NA)
for (i in 1:nrow(DF))  {
  code <- as.character(DF$code[i])
  DF$time[i] <- timing(code, DF$ngrid[i], DF$n_core[i])
}
saveRDS(DF, "multicore.rds")
```

```{r, echo=FALSE}
DF <- readRDS("multicore.rds")
```

```{r, fig.width=7, fig.height=7, echo=FALSE}
library(ggplot2)
ggplot(DF, aes(x = factor(n_core), y = time)) + 
  facet_grid(paste("ngrid =", ngrid) ~ codes) + 
  geom_bar(stat = "identity") + theme_bw() +
  xlab("Number of CPU Cores") + ylab("Elapsed Time (seconds)")
```


