---
title: "Step I. Feature Extraction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE
)
options(width=100)
```

```{r lib}
library(PETLER)
```

We can use the `petler.fpca` function to create the base functions required to run the PETLER algorithm. By default, you only need to provide data in the list format mentioned above. However, you can view the help documentation (`?petler.fpca`) or click [HERE](https://celehs.github.io/PETLER/reference/petler.fpca.html) to customize configurable arguments.

```{r fpca, eval=FALSE}
system.time(obj <- petler.fpca(data_org))
##    user  system elapsed 
## 142.076  18.887  75.564
saveRDS(obj, "step1.rds")
```

```{r, echo=FALSE}
obj <- readRDS("step1.rds")
```

```{r, echo=FALSE}
TrainCode <- data_org$TrainCode
TrainCode[, monthstd := month / fu_time]  
DF.t <- rbind(
  data.frame(code = "pred1", t = with(TrainCode, rep(monthstd, pred1))),
  data.frame(code = "pred2", t = with(TrainCode, rep(monthstd, pred2))),
  data.frame(code = "pred3", t = with(TrainCode, rep(monthstd, pred3))))
DF.d <- rbind(
  cbind(code = "pred1", obj$FPCA$pred1$mean),
  cbind(code = "pred2", obj$FPCA$pred2$mean),
  cbind(code = "pred3", obj$FPCA$pred3$mean))
```

```{r, fig.width=9, fig.height=3, echo=FALSE}
library(ggplot2)
ggplot(DF.t, aes(x = t)) + 
  geom_histogram(aes(y = ..density..), color="gray", fill="white", binwidth = 0.01) + 
  geom_line(aes(x = x, y = f_mu), data = DF.d, colour = "blue") + 
  facet_wrap(~ code, ncol = 3, scales = "free_y") + 
  xlab("x") + theme_bw()
```

```{r, echo=FALSE}
dens1 <- obj$FPCA[[1]]$ValidPred$densities
dens2 <- obj$FPCA[[2]]$ValidPred$densities
dens3 <- obj$FPCA[[3]]$ValidPred$densities
all <- base::intersect(
  base::intersect(
    colnames(dens1)[-1], 
    colnames(dens2)[-1]), 
  colnames(dens3)[-1])
```

```{r, echo=FALSE}
f <- function(k) {
  ValidCode <- data_org$ValidCode
  ValidCode[, monthstd := month / fu_time]  
  DF.t <- rbind(
    data.frame(code = "pred1", t = with(ValidCode[id == all[k], ], rep(monthstd, pred1))),
    data.frame(code = "pred2", t = with(ValidCode[id == all[k], ], rep(monthstd, pred2))),
    data.frame(code = "pred3", t = with(ValidCode[id == all[k], ], rep(monthstd, pred3))))
  DF.d <- rbind(
    data.frame(code = "pred1", x = dens1[, 1], y = dens1[, all[k]]),
    data.frame(code = "pred2", x = dens2[, 1], y = dens2[, all[k]]),
    data.frame(code = "pred3", x = dens3[, 1], y = dens3[, all[k]]))  
  ggplot(DF.t, aes(x = t)) + 
    geom_histogram(aes(y = ..density..), color="gray", fill="white", binwidth = 0.1) + 
    geom_line(aes(x = x, y = y), data = DF.d, colour = "blue") + 
    facet_wrap(~ code, ncol = 3, scales = "free_y") + 
    xlab("x") + ggtitle(paste("ID:", all[k])) + theme_bw()
}
```

Subject-specific densities

```{r, fig.width=9, fig.height=3, echo=FALSE}
f(1)
f(2)
f(3)
```

...
