---
title: "Step II: Model Fitting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = TRUE,
  collapse = TRUE
)
options(width=100)
```

```{r lib}
library(PETLER)
```

First, we load the FPCA results from step I. 

```{r}
obj <- readRDS("step1.rds")
```

We can now run the PETLER algorithm by calling the `petler` function and providing the base object obtained from the previous step. Use `?petler` or click [HERE](https://celehs.github.io/PETLER/reference/petler.html) to view help documentation and configurable arguments.

```{r, eval=FALSE}
system.time(fit <- petler(obj))
##    user  system elapsed 
## 292.297   0.338 292.641
```

```{r, eval=FALSE, echo=FALSE}
saveRDS(fit, "step2.rds")
```

```{r, echo=FALSE}
fit <- readRDS("step2.rds")
```

```{r, include=FALSE}
bgbbest <- fit$bgbbest_FromChengInit_BFGS
colnames(bgbbest)[2] <- "MLE"
DF.wide <- data.frame(i = 1:nrow(bgbbest), bgbbest)
DF.wide
```

```{r, fig.width=8, fig.height=6, echo=FALSE}
library(ggplot2)
DF.long <- tidyr::gather(DF.wide, key = "type", value = "coef", bgbm.init:BIC.Orig)
ggplot(DF.long, aes(x = i, y = coef)) + 
  geom_bar(stat="identity") + 
  facet_wrap(~ type) + 
  theme_bw() + xlab("") + ylab("") 
```

```{r}
# Details of the fitted model
fit$bgbbest_FromChengInit_BFGS
```

```{r}
# C-statistics and adjusted Brier scores of the derived algorithm
fit$Cstat_BrierSc_ChengInit_BFGS
```

```{r}
# A vector of consecutive integers describing the grouping coefficients
fit$group
```

