# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FPC_Kern_S <- function(x, t, N, h1, h2) {
    .Call('_PETLER_FPC_Kern_S', PACKAGE = 'PETLER', x, t, N, h1, h2)
}

FPC_Kern_S_old <- function(x, t, N, h1, h2) {
    .Call('_PETLER_FPC_Kern_S_old', PACKAGE = 'PETLER', x, t, N, h1, h2)
}

